apiVersion: batch/v1
kind: CronJob
metadata:
  name: rivian-databricks
  labels:
    app: rivian-databricks
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rivian-databricks
            image: sween/rivian-databricks:latest
            env:
            - name: RIVIAN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rivian-user-pass
                  key: rivian_password
            - name: RIVIAN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rivian-user-pass
                  key: rivian_username
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_default_region
          restartPolicy: OnFailure